# Линейные модели и нейронные сети. Практическая работа

В этой практической работе пять обязательных задач.

Они помогут понять, что вы действительно усвоили материал модуля. 

Удачи!

## Цели практической работы
Потренироваться в обучении модели:
- линейной регрессии;
- логистической регрессии; 
- многослойного персептрона.

## Что входит в практическую работу

1. Загрузите датасет и ознакомьтесь с ним.
2. Обучите линейную регрессию, включая признаки с нулевым весом и без них. Замерьте качество.
3. Обучите случайный лес. Замерьте качество.
4. Обучите многослойный перцептрон. Замерьте качество.
5. Реализуйте стратегию голосования. Замерьте качество.

## Что оценивается

* Выполнены все задания. В каждом:
 * в коде нет ручных перечислений, все действия автоматизированы;
 * результаты вычислений и применённых операций корректны;
 * ответы на вопросы, где требуется, корректны и обоснованы; 
 * код читабелен: переменным даны осмысленные названия, соблюдены отступы и правила расстановки пробелов. Стилизация кода соответствует рекомендациям [PEP 8](https://pythonworld.ru/osnovy/pep-8-rukovodstvo-po-napisaniyu-koda-na-python.html).
 
* Репозиторий проекта оформлен корректно:
 * содержит осмысленные коммиты, содержащие конкретные реализованные фичи;
 * ветки названы согласно назначению;
 * файлы, не связанные с проектом, не хранятся в репозитории.

## Как отправить работу на проверку

Сдайте практическую работу этого модуля через систему контроля версий Git сервиса Skillbox GitLab. После загрузки работы на проверку напишите об этом в личном кабинете своему куратору.

## Задача

Постройте модель классификации, определяющую категорию цены / цену подержанного автомобиля в зависимости от характеристик транспортного средства. 

Используйте датасет из коллекции подержанных автомобилей, выставленных на продажу в Соединенных Штатах. Он уже подготовлен, без выбросов и с категориальными фичами, преобразованными с помощью one hot encoding, и количественными фичами, стандартизированными с помощью скейлеров.

### Описание датасета:
- `id`— идентификатор записи;
- `is_manufacturer_name`— признак производителя автомобиля;

- `region_*`— регион;
- `x0_*`— тип топлива;
- `manufacturer_*`— производитель;
- `short_model_*`— сокращённая модель автомобиля;
- `title_status_*`— статус;
- `transmission_*`— коробка передач;
- `state_*`— штат;
- `age_category_*`— возрастная категория автомобиля;

- `std_scaled_odometer`— количество пройденных миль (после стандартизации);
- `year_std`— год выпуска (после стандартизации);
- `lat_std`— широта (после стандартизации);
- `long_std`— долгота (после стандартизации);
- `odometer/price_std`— отношение стоимости к пробегу автомобиля (после стандартизации);
- `desc_len_std`— количество символов в тексте объявления о продаже (после стандартизации);
- `model_in_desc_std`— количество наименований модели автомобиля в тексте объявления о продаже (после стандартизации);
- `model_len_std`— длина наименования автомобиля (после стандартизации);
- `model_word_count_std`— количество слов в наименовании автомобиля (после стандартизации);
- `month_std`— номер месяца размещения объявления о продаже автомобиля (после стандартизации);
- `dayofweek_std`— день недели размещения объявления о продаже автомобиля (после стандартизации);
- `diff_years_std`— количество лет между годом производства автомобиля и годом размещения объявления о продаже автомобиля (после стандартизации);
- `price`— стоимость;
- `price_category`— категория цены.

## Обязательные задачи

In [24]:
import matplotlib.pyplot as plt
import pandas as pd

from sklearn.linear_model import LogisticRegression, LinearRegression
from sklearn.metrics import accuracy_score, confusion_matrix, mean_absolute_error
from sklearn.model_selection import train_test_split 
from sklearn.neural_network import MLPClassifier

In [25]:
df = pd.read_csv('C:/Users/User/Desktop/Python/Python/ds-intro/ds-intro/23_linear_model/data/vehicles_dataset_prepared.csv', sep = ',')
df.head()

id  price price_category  is_audi  is_ford  is_chevrolet  \
0  7308295377  54990           high        0        0             0   
1  7316380095  16942         medium        0        1             0   
2  7313733749  35590           high        0        0             0   
3  7308210929  14500         medium        0        0             0   
4  7303797340  14590         medium        0        0             0   

   is_toyota  x0_diesel  x0_electric  x0_gas  ...  long_std  year_std  \
0          0        1.0          0.0     0.0  ...  0.484245  1.322394   
1          0        0.0          0.0     0.0  ...  1.110800  0.695973   
2          0        0.0          0.0     1.0  ...  0.531185  0.852578   
3          1        0.0          0.0     1.0  ...  0.853562  0.226157   
4          0        0.0          0.0     0.0  ...  0.557607  0.069552   

   odometer/price_std  desc_len_std  model_in_desc_std  model_len_std  \
0           -0.510784      0.632075          -0.155788       1.163032   
1           -0.402947     -0.646781          -0.155788       0.932087   
2           -0.514480      0.560744          -0.155788       0.470197   
3           -0.241883      0.180435          -0.155788      -0.915473   
4           -0.333074      0.766366          -0.155788       1.163032   

   model_word_count_std  month_std  dayofweek_std  diff_years_std  
0              1.910669  -0.615846       1.120284       -1.322394  
1              1.235799   1.623784      -1.374972       -0.695973  
2              0.560930  -0.615846      -0.376870       -0.852578  
3             -0.788810  -0.615846       1.120284       -0.226157  
4              1.910669  -0.615846       0.122182       -0.069552  

[5 rows x 1463 columns]

**Задача 1. Линейная регрессия**

Вспомните задачу по предсказанию стоимости подержанного автомобиля. Попробуйте обучить модель линейной регрессии для предсказания цены автомобиля (колонка `price`). Для этого сделайте шаги:

- подготовьте данные: удалите колонки, которые косвенно содержат информацию о целевой переменной (`odometer/price_std`, `price_category`);
- разделите выборку на треин и тест в отношении 70/30;
- обучите модель линейной регрессии с дефолтными параметрами;
- посчитайте значение метрики mae на тестовой выборке для линейной регрессии;
- выведите получившиеся коэффициенты линейной регрессии при каждом параметре обучающей выборки с помощью метода `coef_` (есть ли коэффициенты, которые равны нулю? Если есть, выведите названия фичей с нулевым коэффициентом);
- удалите фичи, коэффициенты которых равны нулю; переобучите модель; убедитесь, что значение метрики не изменилось.



In [26]:
df_prepared = df.copy()
df_prepared = df_prepared.drop(['odometer/price_std', 'price_category'], axis=1)
x = df_prepared.drop(['price'], axis=1)
y = df_prepared['price']

In [27]:
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.3, random_state=42
)    #делим выборку 70 на 30

In [28]:
lr = LinearRegression()
lr.fit(x_train, y_train)  #обучаем модель

LinearRegression()

In [29]:
y_pred = lr.predict(x_test)

In [30]:
mae = mean_absolute_error(y_test, y_pred)
print("MAE линейной регрессии:", mae)

MAE линейной регрессии: 4600.341121031729


In [31]:
coeffs = pd.Series(lr.coef_, index=x_train.columns)
print("Коэффициенты модели:\n", coeffs)

Коэффициенты модели:
 id                         0.000006
is_audi                  254.296466
is_ford                 1073.906608
is_chevrolet            -184.762944
is_toyota                471.500231
                           ...     
model_len_std             25.182269
model_word_count_std     643.950518
month_std               -166.691605
dayofweek_std             23.050437
diff_years_std         -2803.982517
Length: 1460, dtype: float64


In [32]:
zero_coeffs = coeffs[coeffs == 0].index.tolist()
print("Фичи с нулевыми коэффициентами:", zero_coeffs)

Фичи с нулевыми коэффициентами: ['manufacturer_ferrari']


In [33]:
if zero_coeffs:
    x_train_reduced = x_train.drop(columns=zero_coeffs)
    x_test_reduced = x_test.drop(columns=zero_coeffs)

    lr2 = LinearRegression()
    lr2.fit(x_train_reduced, y_train)

    y_pred2 = lr2.predict(x_test_reduced)

    mae2 = mean_absolute_error(y_test, y_pred2)
    print("MAE после удаления нулевых фич:", mae2)

MAE после удаления нулевых фич: 4600.341120494278


**Задача 2. Логистическая регрессия**

Теперь в рамках тех же данных попробуйте предсказать `price_category` с помощью алгоритма логистической регрессии. Предварительно из датафрейма удалите переменные, в которых косвенно содержится информация о целевой переменной (`odometer/price_std`, `price`). 

Для обученной модели:

- рассчитайте и выведите метрику качества (accuracy) на тренировочной выборке;
- сделайте предикт на тестовых данных и положите его в переменную `logreg_pred`;
- рассчитайте и выведите accuracy и confusion_matrix на тестовой выборке.

Обратите внимание, что это задание засчитывается, если: 
- accuracy на тренировочной выборке > 87%;
- accuracy на тестовой выборке > 75.5%.

Для улучшения метрики можно преобразовывать входные данные и тюнить параметры логистической регрессии.

In [56]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix

In [61]:
df = pd.read_csv('C:/Users/User/Desktop/Python/Python/ds-intro/ds-intro/23_linear_model/data/vehicles_dataset_prepared.csv', sep = ',')
df.head()


id  price price_category  is_audi  is_ford  is_chevrolet  \
0  7308295377  54990           high        0        0             0   
1  7316380095  16942         medium        0        1             0   
2  7313733749  35590           high        0        0             0   
3  7308210929  14500         medium        0        0             0   
4  7303797340  14590         medium        0        0             0   

   is_toyota  x0_diesel  x0_electric  x0_gas  ...  long_std  year_std  \
0          0        1.0          0.0     0.0  ...  0.484245  1.322394   
1          0        0.0          0.0     0.0  ...  1.110800  0.695973   
2          0        0.0          0.0     1.0  ...  0.531185  0.852578   
3          1        0.0          0.0     1.0  ...  0.853562  0.226157   
4          0        0.0          0.0     0.0  ...  0.557607  0.069552   

   odometer/price_std  desc_len_std  model_in_desc_std  model_len_std  \
0           -0.510784      0.632075          -0.155788       1.163032   
1           -0.402947     -0.646781          -0.155788       0.932087   
2           -0.514480      0.560744          -0.155788       0.470197   
3           -0.241883      0.180435          -0.155788      -0.915473   
4           -0.333074      0.766366          -0.155788       1.163032   

   model_word_count_std  month_std  dayofweek_std  diff_years_std  
0              1.910669  -0.615846       1.120284       -1.322394  
1              1.235799   1.623784      -1.374972       -0.695973  
2              0.560930  -0.615846      -0.376870       -0.852578  
3             -0.788810  -0.615846       1.120284       -0.226157  
4              1.910669  -0.615846       0.122182       -0.069552  

[5 rows x 1463 columns]

In [62]:
df_prepared = df.drop(['id','price','odometer/price_std'], axis=1)

In [63]:
x = df_prepared.drop('price_category', axis=1)  
y = df_prepared['price_category']

In [64]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42, stratify=y)

In [65]:
logreg = LogisticRegression(
    C=5,
    penalty='l2',
    max_iter=2000,      
    solver='lbfgs',
    multi_class='multinomial'
)

In [66]:
logreg = LogisticRegression()
logreg.fit(x_train, y_train)
train_acc = accuracy_score(y_train, logreg.predict(x_train))
print("Accuracy на train:", train_acc)

Accuracy на train: 0.8512020792722547


C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [67]:

test_acc = accuracy_score(y_test, logreg.predict(x_test))
cm = confusion_matrix(y_test, logreg.predict(x_test))

print("Accuracy на test:", test_acc)
print("Матрица ошибок:\n", cm)

Accuracy на test: 0.7806652806652806
Матрица ошибок:
 [[540  13  87]
 [ 23 508 109]
 [ 76 114 454]]


**Задача 3. Многослойный персептрон**

Решите задачу, поставленную в предыдущем задании, применив модель многослойного персептрона. С помощью данного алгоритма добейтесь лучших значений точности на тренировочной и тестовой выборках, чем на логистической регрессии. 

Увеличение точности в данном задании, по сравнению с предыдущим, должно быть больше увеличения 0.01 по метрике accuracy.

In [68]:
df = pd.read_csv('C:/Users/User/Desktop/Python/Python/ds-intro/ds-intro/23_linear_model/data/vehicles_dataset_prepared.csv', sep = ',')
df.head()

id  price price_category  is_audi  is_ford  is_chevrolet  \
0  7308295377  54990           high        0        0             0   
1  7316380095  16942         medium        0        1             0   
2  7313733749  35590           high        0        0             0   
3  7308210929  14500         medium        0        0             0   
4  7303797340  14590         medium        0        0             0   

   is_toyota  x0_diesel  x0_electric  x0_gas  ...  long_std  year_std  \
0          0        1.0          0.0     0.0  ...  0.484245  1.322394   
1          0        0.0          0.0     0.0  ...  1.110800  0.695973   
2          0        0.0          0.0     1.0  ...  0.531185  0.852578   
3          1        0.0          0.0     1.0  ...  0.853562  0.226157   
4          0        0.0          0.0     0.0  ...  0.557607  0.069552   

   odometer/price_std  desc_len_std  model_in_desc_std  model_len_std  \
0           -0.510784      0.632075          -0.155788       1.163032   
1           -0.402947     -0.646781          -0.155788       0.932087   
2           -0.514480      0.560744          -0.155788       0.470197   
3           -0.241883      0.180435          -0.155788      -0.915473   
4           -0.333074      0.766366          -0.155788       1.163032   

   model_word_count_std  month_std  dayofweek_std  diff_years_std  
0              1.910669  -0.615846       1.120284       -1.322394  
1              1.235799   1.623784      -1.374972       -0.695973  
2              0.560930  -0.615846      -0.376870       -0.852578  
3             -0.788810  -0.615846       1.120284       -0.226157  
4              1.910669  -0.615846       0.122182       -0.069552  

[5 rows x 1463 columns]

In [70]:
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier

In [71]:
df_prepared = df.drop(['id', 'price', 'odometer/price_std'], axis=1)

In [73]:
x = df_prepared.drop('price_category', axis=1)
y = df_prepared['price_category']

In [74]:
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42, stratify=y
)

In [75]:
num_cols = [
    'std_scaled_odometer', 'year_std', 'lat_std', 'long_std', 
    'desc_len_std', 'model_in_desc_std', 'model_len_std', 
    'model_word_count_std', 'month_std', 'dayofweek_std', 'diff_years_std'
]

scaler = StandardScaler()
x_train[num_cols] = scaler.fit_transform(x_train[num_cols])
x_test[num_cols] = scaler.transform(x_test[num_cols])

In [76]:
mlp = MLPClassifier(
    hidden_layer_sizes=(128, 64),  
    activation='relu',            
    solver='adam',                
    max_iter=1000,
    random_state=42
)

In [77]:
mlp.fit(x_train, y_train)

MLPClassifier(hidden_layer_sizes=(128, 64), max_iter=1000, random_state=42)

In [79]:
train_acc = accuracy_score(y_train, mlp.predict(x_train))
test_acc = accuracy_score(y_test, mlp.predict(x_test))
cm = confusion_matrix(y_test, mlp.predict(x_test))

print("Accuracy на train:", train_acc)
print("Accuracy на test:", test_acc)
print("Матрица ошибок:\n", cm)

Accuracy на train: 1.0
Accuracy на test: 0.7806652806652806
Матрица ошибок:
 [[532  10  98]
 [ 19 505 116]
 [ 72 107 465]]


**Задача 4. Сравнение с древовидными моделями**

Обучите модель случайного леса на тех же данных для предсказания `price_category`. Сравните качество с моделью логистической регрессии и многослойного персептрона. Словами опишите, какая из моделей в каких случаях работает лучше по результатам на тестовой выборке, обоснуйте свой выбор.

In [80]:
from sklearn.ensemble import RandomForestClassifier

In [81]:
df = pd.read_csv('C:/Users/User/Desktop/Python/Python/ds-intro/ds-intro/23_linear_model/data/vehicles_dataset_prepared.csv', sep = ',')
df.head()

id  price price_category  is_audi  is_ford  is_chevrolet  \
0  7308295377  54990           high        0        0             0   
1  7316380095  16942         medium        0        1             0   
2  7313733749  35590           high        0        0             0   
3  7308210929  14500         medium        0        0             0   
4  7303797340  14590         medium        0        0             0   

   is_toyota  x0_diesel  x0_electric  x0_gas  ...  long_std  year_std  \
0          0        1.0          0.0     0.0  ...  0.484245  1.322394   
1          0        0.0          0.0     0.0  ...  1.110800  0.695973   
2          0        0.0          0.0     1.0  ...  0.531185  0.852578   
3          1        0.0          0.0     1.0  ...  0.853562  0.226157   
4          0        0.0          0.0     0.0  ...  0.557607  0.069552   

   odometer/price_std  desc_len_std  model_in_desc_std  model_len_std  \
0           -0.510784      0.632075          -0.155788       1.163032   
1           -0.402947     -0.646781          -0.155788       0.932087   
2           -0.514480      0.560744          -0.155788       0.470197   
3           -0.241883      0.180435          -0.155788      -0.915473   
4           -0.333074      0.766366          -0.155788       1.163032   

   model_word_count_std  month_std  dayofweek_std  diff_years_std  
0              1.910669  -0.615846       1.120284       -1.322394  
1              1.235799   1.623784      -1.374972       -0.695973  
2              0.560930  -0.615846      -0.376870       -0.852578  
3             -0.788810  -0.615846       1.120284       -0.226157  
4              1.910669  -0.615846       0.122182       -0.069552  

[5 rows x 1463 columns]

In [82]:
df_prepared = df.drop(['id', 'price', 'odometer/price_std'], axis=1)

In [87]:
x = df_prepared.drop('price_category', axis=1)
y = df_prepared['price_category']

x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42, stratify=y
)

In [88]:
rf = RandomForestClassifier(random_state=42)
rf.fit(x_train, y_train)

RandomForestClassifier(random_state=42)

In [89]:
train_acc = accuracy_score(y_train, rf.predict(x_train))
test_acc = accuracy_score(y_test, rf.predict(x_test))
cm = confusion_matrix(y_test, rf.predict(x_test))

print("Random Forest — Accuracy на train:", train_acc)
print("Random Forest — Accuracy на test:", test_acc)
print("Матрица ошибок:\n", cm)

Random Forest — Accuracy на train: 1.0
Random Forest — Accuracy на test: 0.7780665280665281
Матрица ошибок:
 [[543  15  82]
 [ 11 547  82]
 [ 95 142 407]]


**Задача 5. Стратегия голосования**

Реализуйте стратегию голосования для предсказания целевой переменной.
Голосование в задаче классификации — это когда несколько моделей выдают свои предикты, и финальным выбирается тот предикт, который предсказали большинство моделей.

Для реализации этой стратегии проделайте следующее:

- сохраните предсказания каждой из моделей (случайный лес, многослойный персептрон, логистическая регрессия) для тестовой выборки в датафрейм `pred_df`;
- в четвёртую колонку `target` положите тот класс, который предсказало большинство классификаторов; например, если в строке были значения `high, medium, medium`, в `target` нужно положить `medium`;

     если в строке три разных класса (`high, medium, low`), придумайте свою стратегию по выбору значения; самая простая стратегия — выбрать рандомно одно значение из трёх;

- посчитайте точность предсказания с помощью голосования; выведите значения метрик accuracy и confusion_matrix.

Добейтесь значения точности > 78%.

In [110]:
import pandas as pd
from pandas.core.apply import frame_apply
import numpy as np
from sklearn.metrics import accuracy_score, confusion_matrix

In [111]:
logreg_preds = logreg.predict(x_test)
mlp_preds = mlp.predict(x_test)
rf_preds = rf.predict(x_test)

In [112]:
pred_df = pd.DataFrame({
    'logreg': logreg_preds,
    'mlp': mlp_preds,
    'rf': rf_preds
})

In [113]:
def majority_vote(row):
    votes = [v for v in row.values if v is not None and v == v]
    if len(votes) == 0:
        return np.random.choice(['low', 'medium', 'high'])  

    unique, counts = np.unique(votes, return_counts=True)
    max_count = counts.max()

In [114]:
def majority_vote(row):
    votes = row.values
    unique, counts = np.unique(votes, return_counts=True)
    max_count = counts.max()
    if np.sum(counts == max_count) == 1:
        return unique[np.argmax(counts)]
    else:
        
        return np.random.choice(votes)

In [115]:
pred_df['target'] = pred_df.apply(majority_vote, axis=1)

In [116]:
accuracy = accuracy_score(y_test, pred_df['target'])
cm = confusion_matrix(y_test, pred_df['target'])

print("Voting Accuracy:", accuracy)
print("Confusion matrix:\n", cm)

Voting Accuracy: 0.8050935550935551
Confusion matrix:
 [[547  13  80]
 [ 18 530  92]
 [ 66 106 472]]


**Примечание**

В этой практической работе перед вами встал выбор: включать ли колонку `id`. При удалении данной колонки во время обучения логистической регрессии качество заметно улучшается.

Обучать любую модель (будь то логистическая, линейная регрессия или древовидный алгоритм) на данных айдишников не считается хорошей практикой. Как правило, между `id` и целевой переменной не должно быть никаких взаимосвязей. Включая колонку `id` в качества атрибута в обучение, вы стараетесь подогнать результаты своей модели под айдишники записей. Таким образом модель обучится на некотором наборе частных случаев и, возможно, не обратит внимание на общие зависимости.   