# Машинное обучение. Практическая работа

В этой практической работе четыре обязательные задачи.

Они помогут понять, что вы действительно усвоили материал модуля. 


Удачи!

## Цели практической работы

Научиться:
- обучать модели, основанные на деревьях решений;
- научиться оценивать и увеличивать их качество.

## Что входит в практическую работу

1. Загрузите датасет и ознакомьтесь с ним.
2. Подготовьте базовую модель дерева решений и измерьте её качество.
3. Подготовьте базовую модель случайного леса и измерьте её качество.
4. Увеличьте точность модели случайного леса на тестовых данных.
5. Проведите анализ влияния признаков на модель.

## Что оценивается

* Выполнены все четыре задачи. Для каждой:
 * в коде нет ручных перечислений, все действия автоматизированы;
 * результаты вычислений и применённых операций корректны;
 * ответы на вопросы, где требуется, корректны и обоснованы; 
 * код читабелен: переменным даны осмысленные названия, соблюдены отступы и правила расстановки пробелов; стилизация кода соответствует рекомендациям [PEP 8](https://pythonworld.ru/osnovy/pep-8-rukovodstvo-po-napisaniyu-koda-na-python.html).

* Репозиторий проекта оформлен корректно:
 * содержит осмысленные коммиты, содержащие конкретные реализованные фичи;
 * ветки названы согласно назначению;
 * файлы, не связанные с проектом, не хранятся в репозитории.


## Как отправить работу на проверку

Сдайте практическую работу этого модуля через систему контроля версий Git сервиса Skillbox GitLab. После загрузки работы на проверку напишите об этом в личном кабинете своему куратору.

## Обязательные задачи

### Описание датасета:
- `id`— идентификатор записи;
- `is_manufacturer_name`— признак производителя автомобиля;

- `region_*`— регион;
- `x0_*`— тип топлива;
- `manufacturer_*`— производитель;
- `short_model_*`— сокращённая модель автомобиля;
- `title_status_*`— статус;
- `transmission_*`— коробка передач;
- `state_*`— штат;
- `age_category_*`— возрастная категория автомобиля;

- `std_scaled_odometer`— количество пройденных миль (после стандартизации);
- `year_std`— год выпуска (после стандартизации);
- `lat_std`— широта (после стандартизации);
- `long_std`— долгота (после стандартизации);
- `odometer/price_std`— отношение стоимости к пробегу автомобиля (после стандартизации);
- `desc_len_std`— количество символов в тексте объявления о продаже (после стандартизации);
- `model_in_desc_std`— количество наименований модели автомобиля в тексте объявления о продаже (после стандартизации);
- `model_len_std`— длина наименования автомобиля (после стандартизации);
- `model_word_count_std`— количество слов в наименовании автомобиля (после стандартизации);
- `month_std`— номер месяца размещения объявления о продаже автомобиля (после стандартизации);
- `dayofweek_std`— день недели размещения объявления о продаже автомобиля (после стандартизации);
- `diff_years_std`— количество лет между годом производства автомобиля и годом размещения объявления о продаже автомобиля (после стандартизации);

- `price`— стоимость;
- `price_category`— категория цены.

1. Подготовка базовой модели

Обучите простую модель классификации с помощью DecisionTreeClassifier на данных из датасета vehicles_dataset_prepared.csv. Для этого сделайте шаги:

1. Обучите модель дерева решений с зафиксированным random_state на тренировочной выборке.
2. Сделайте предикт на тестовой выборке.
3. Замерьте точность на тестовой выборке и выведите матрицу ошибок. 
4. Удалите фичи с нулевыми весами по feature_importance из тренировочной и тестовой выборок.
5. Заново обучите модель и измерьте качество.

In [2]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split 
from sklearn.metrics import accuracy_score, confusion_matrix 

In [3]:
df = pd.read_csv('C:/Users/User/Desktop/Python/Python/ds-intro/ds-intro/22_machine_learning/homework/data/vehicles_dataset_prepared.csv', sep = ',')

df_prepared = df.copy()
df_prepared = df_prepared.drop(['price', 'odometer/price_std'], axis=1)

x = df_prepared.drop(['price_category'], axis=1)
y = df_prepared['price_category']

x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.3, random_state=42
)

In [4]:
clf = DecisionTreeClassifier(random_state=42)
clf.fit(x_train, y_train)

DecisionTreeClassifier(random_state=42)

In [5]:
predicted_train = clf.predict(x_train)
predicted_test = clf.predict(x_test)

In [6]:
print("Accuracy на train:", accuracy_score(y_train, predicted_train))
print("Accuracy на test:", accuracy_score(y_test, predicted_test))
print("Матрица ошибок:\n", confusion_matrix(y_test, predicted_test))

Accuracy на train: 1.0
Accuracy на test: 0.6704781704781705
Матрица ошибок:
 [[738  54 205]
 [ 46 688 219]
 [198 229 509]]


In [7]:
accuracy_score(y_test, predicted_test)

0.6704781704781705

In [8]:
confusion_matrix(y_test, predicted_test)

array([[738,  54, 205],
       [ 46, 688, 219],
       [198, 229, 509]])

In [9]:
importances = clf.feature_importances_
zero_features = [col for col, imp in zip(x_train.columns, importances) if imp == 0]
print("Фичи с нулевой важностью:", zero_features)

Фичи с нулевой важностью: ['short_model_-benz', 'short_model_1', 'short_model_124', 'short_model_128i', 'short_model_135i', 'short_model_163869', 'short_model_1928', 'short_model_1951', 'short_model_1954', 'short_model_1960s', 'short_model_1966', 'short_model_1968', 'short_model_1972', 'short_model_1977', 'short_model_1978', 'short_model_198.5', 'short_model_1988', 'short_model_1994', 'short_model_1999', 'short_model_2', 'short_model_2000', 'short_model_2002', 'short_model_2006', 'short_model_2007', 'short_model_2008', 'short_model_2009', 'short_model_2012', 'short_model_2015', 'short_model_2016', 'short_model_2017', 'short_model_2018', 'short_model_210', 'short_model_240', 'short_model_2500hd', 'short_model_280zx', 'short_model_3', 'short_model_3-series', 'short_model_3-window', 'short_model_3.2', 'short_model_300', 'short_model_300-series', 'short_model_300c', 'short_model_300s', 'short_model_300zx', 'short_model_3100', 'short_model_318i', 'short_model_320i', 'short_model_323i', 'sho

In [10]:
x_train_reduced = x_train.drop(columns=zero_features)
x_test_reduced = x_test.drop(columns=zero_features)

clf2 = DecisionTreeClassifier(random_state=42)
clf2.fit(x_train_reduced, y_train)

predicted_test2 = clf2.predict(x_test_reduced)

print("Accuracy после удаления:", accuracy_score(y_test, predicted_test2))
print("Матрица ошибок после удаления:\n", confusion_matrix(y_test, predicted_test2))

Accuracy после удаления: 0.6725571725571725
Матрица ошибок после удаления:
 [[730  54 213]
 [ 42 696 215]
 [192 229 515]]


2. Подготовка модели случайного леса

Обучите простую модель классификации с помощью RandomForestClassifier. Для этого на новых урезанных семплах тренировочной и тестовой выборок обучите модель случайного леса с зафиксированным random_state=50. 

In [11]:
from sklearn.ensemble import RandomForestClassifier


In [12]:
x_train_reduced = x_train.drop(columns=zero_features)
x_test_reduced = x_test.drop(columns=zero_features)

In [13]:
rf = RandomForestClassifier(random_state=50)
rf.fit(x_train_reduced, y_train)
y_pred_rf = rf.predict(x_test_reduced)
print("Точность Random Forest:", accuracy_score(y_test, y_pred_rf))
print("Матрица ошибок:\n", confusion_matrix(y_test, y_pred_rf))

Точность Random Forest: 0.7418572418572419
Матрица ошибок:
 [[793  37 167]
 [ 16 789 148]
 [165 212 559]]


2. Сделайте предикт, посчитайте точность модели и матрицу ошибок. Сравните с предыдущей моделью дерева решений. Есть ли случаи, когда модель из пункта 1 отрабатывает лучше, чем модель случайного леса?

In [14]:
print("Точность Random Forest:", accuracy_score(y_test, y_pred_rf))
print("Матрица ошибок:\n", confusion_matrix(y_test, y_pred_rf))

Точность Random Forest: 0.7418572418572419
Матрица ошибок:
 [[793  37 167]
 [ 16 789 148]
 [165 212 559]]


3. Тюнинг модели случайного леса

Увеличьте точность модели на тестовом датасете RandomForestClassifier c помощью тюнинга параметров. 

Параметры, которые можно настраивать для увеличения точности:
```
    `bootstrap'
    'max_depth'
    'max_features'
    'min_samples_leaf'
    'min_samples_split'
    'random_state'
    'n_estimators'

```

С описанием каждого из параметров можно ознакомиться [в документации](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html).

Задание засчитывается, если значение метрики строго выше 0.76 на тестовом датасете.

In [15]:
from sklearn.model_selection import GridSearchCV

In [ ]:
rf = RandomForestClassifier(random_state=50)
param_grid = {
    'n_estimators': [100, 200, 300],
    'max_depth': [10, 20, None],
    'max_features': ['sqrt', 'log2'],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'bootstrap': [True, False]
}

grid_search = GridSearchCV(
    estimator=rf,
    param_grid=param_grid,
    cv=3,
    n_jobs=-1,
    verbose=2,
    scoring='accuracy'
)

grid_search.fit(x_train_reduced, y_train)

Fitting 3 folds for each of 324 candidates, totalling 972 fits


In [ ]:
best_rf = grid_search.best_estimator_
print("Лучшие параметры:", grid_search.best_params_)

In [ ]:
y_pred_best = best_rf.predict(x_test_reduced)
print("Точность на тесте:", accuracy_score(y_test, y_pred_best))
print("Матрица ошибок:\n", confusion_matrix(y_test, y_pred_best))

4. Анализ влияния фичей на модель

До этого в задачах вы работали над подготовленным датасетом, где фичи были заранее извлечены из текстовых переменных, отскейлены и пропущены через OneHotEncoder. Сравним, какой была бы предсказательная способность модели, если бы мы использовали только сырые данные из исходного датасета. Для этого проделайте следующие шаги:

1. Загрузите датасет `vehicles_dataset_old.csv`.
2. Удалите из него переменную `price` и все строковые колонки. Дерево решений и случайный лес не умеют самостоятельно работать со строковыми значениями.
3. Сформируйте x_train и x_test так же, как они были сформированы в предыдущих заданиях.
4. Обучите свою лучшую модель случайного леса на новых данных и замерьте качество. Убедитесь, что оно ухудшилось.
5. Найдите три фичи, которые лучшим образом повлияли на предсказательную способность модели.

In [18]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np

df_old = pd.read_csv('C:/Users/User/Desktop/Python/Python/ds-intro/ds-intro/22_machine_learning/homework/data/vehicles_dataset_old.csv', sep = ',')
df_old.head()

id                                                url  \
0  7308295377  https://chattanooga.craigslist.org/ctd/d/chatt...   
1  7316380095  https://newjersey.craigslist.org/ctd/d/carlsta...   
2  7313733749  https://reno.craigslist.org/ctd/d/atlanta-2017...   
3  7308210929  https://fayetteville.craigslist.org/ctd/d/rale...   
4  7303797340  https://knoxville.craigslist.org/ctd/d/knoxvil...   

         region                           region_url  price  year  \
0   chattanooga   https://chattanooga.craigslist.org  54990  2020   
1  north jersey     https://newjersey.craigslist.org  16942  2016   
2  reno / tahoe          https://reno.craigslist.org  35590  2017   
3  fayetteville  https://fayetteville.craigslist.org  14500  2013   
4     knoxville     https://knoxville.craigslist.org  14590  2012   

  manufacturer                   model    fuel  odometer title_status  \
0          ram  2500 crew cab big horn  diesel     27442        clean   
1         ford    explorer 4wd 4dr xlt   other     60023        clean   
2   volkswagen        golf r hatchback     gas     14048        clean   
3       toyota                    rav4     gas    117291        clean   
4          bmw  1 series 128i coupe 2d   other     80465        clean   

  transmission                                          image_url  \
0        other  https://images.craigslist.org/00N0N_1xMPvfxRAI...   
1    automatic  https://images.craigslist.org/00x0x_26jl9F0cnL...   
2        other  https://images.craigslist.org/00y0y_eeZjWeiSfb...   
3    automatic  https://images.craigslist.org/00606_iGe5iXidib...   
4        other  https://images.craigslist.org/00F0F_5UAXmOzC18...   

                                         description state        lat  \
0  Carvana is the safer way to buy a car During t...    tn  35.060000   
1  ***Call Us for more information at: 201-635-14...    nj  40.821805   
2  Carvana is the safer way to buy a car During t...    ca  33.779214   
3  2013 Toyota RAV4 XLE 4dr SUV     Offered by: R...    nc  35.715954   
4  Carvana is the safer way to buy a car During t...    tn  35.970000   

        long              posting_date price_category  \
0 -85.250000  2021-04-17T12:30:50-0400           high   
1 -74.061962  2021-05-03T15:40:21-0400         medium   
2 -84.411811  2021-04-28T03:52:20-0700           high   
3 -78.655304  2021-04-17T10:08:57-0400         medium   
4 -83.940000  2021-04-08T15:10:56-0400         medium   

                        date  
0  2021-04-17 16:30:50+00:00  
1  2021-05-03 19:40:21+00:00  
2  2021-04-28 10:52:20+00:00  
3  2021-04-17 14:08:57+00:00  
4  2021-04-08 19:10:56+00:00

Удаляем из него переменную price и все строковые колонки.

In [20]:
y = df_old['price']
x = df_old.drop(['price'], axis=1)  
x = x.select_dtypes(include=[np.number])  

In [25]:
print("Оставшиеся колонки после удаления строковых:")
print(x.columns.tolist())

Оставшиеся колонки после удаления строковых:
['id', 'year', 'odometer', 'lat', 'long']


In [22]:
x_train, x_test, y_train, y_test = train_test_split(
    x, y,
    test_size=0.3,
    random_state=42
)

In [36]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score

rf = RandomForestRegressor(n_estimators=100, random_state=42, n_jobs=-1)
rf.fit(x_train, y_train)

RandomForestRegressor(n_jobs=-1, random_state=42)

In [31]:
y_pred = rf.predict(x_test)


In [32]:
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

In [33]:
print(f"RMSE: {rmse:.2f}")
print(f"R²: {r2:.4f}")

RMSE: 8709.87
R²: 0.5152


In [38]:
importances = rf.feature_importances_
feature_names = x_train.columns

importance_df = pd.DataFrame({
    'feature': feature_names,
    'importance': importances
}).sort_values('importance', ascending=False)


top_3_features = importance_df.head(3)
print("Топ-3 наиболее важных признака:")
print(top_3_features)

Топ-3 наиболее важных признака:
    feature  importance
1      year    0.421821
2  odometer    0.201726
4      long    0.130001
